<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>uap10.0</TargetFramework>
    <OutputType>Exe</OutputType>
    <RuntimeIdentifier>win10-x64</RuntimeIdentifier>
    <ApplicationDisplayName>GTA V News</ApplicationDisplayName>
    <PackageDisplayName>GTA V News</PackageDisplayName>
    <RootNamespace>GTAVNews</RootNamespace>
  </PropertyGroup>
</Project>