name: Build GTA V News
on:
  schedule:
    - cron: '0 0 1 */2 *'
  workflow_dispatch:
jobs:
  build:
    runs-on: windows-latest
    timeout-minutes: 45
    steps:
      - uses: actions/checkout@v5
      - name: Build & Package
        shell: cmd
        run: msbuild GTAVNews.csproj /p:Configuration=Release /p:Platform=x64 /t:Publish /p:UapAppxPackageBuildMode=SideloadOnly /p:AppxBundle=Never
      - name: Upload MSIX
        uses: actions/upload-artifact@v4
        with:
          name: GTAVNews-MSIX
          path: '**/*.msix'